"""
PDF Service - WeasyPrint + Jinja2 for styled PDF generation.

Design decisions:
- Jinja2 templates stored in backend/templates/
- Professional CSS styling embedded in the PDF template
- Supports custom metadata (author, date, classification)
- Returns bytes for direct HTTP streaming
"""

from __future__ import annotations

import io
from datetime import datetime
from pathlib import Path

import structlog
from jinja2 import Environment, FileSystemLoader
from weasyprint import HTML

logger = structlog.get_logger(__name__)

# Template directory
TEMPLATE_DIR = Path(__file__).parent.parent / "templates"


class PDFService:
    """Service for generating styled PDF reports from HTML content."""

    def __init__(self) -> None:
        self._jinja_env = Environment(
            loader=FileSystemLoader(str(TEMPLATE_DIR)),
            autoescape=True,
        )

    def generate_pdf(
        self,
        html_content: str,
        title: str = "NetShield Security Report",
        metadata: dict | None = None,
    ) -> bytes:
        """
        Generate a PDF from HTML content using WeasyPrint.

        Args:
            html_content: The report body HTML (from AI or TipTap editor)
            title: Report title for the cover page
            metadata: Optional dict with author, date, classification, etc.

        Returns:
            PDF file bytes
        """
        meta = metadata or {}
        template = self._jinja_env.get_template("report_base.html")

        full_html = template.render(
            title=title,
            content=html_content,
            author=meta.get("author", "NetShield Dashboard"),
            date=meta.get("date", datetime.now().strftime("%Y-%m-%d %H:%M")),
            classification=meta.get("classification", "INTERNAL"),
            footer_text=meta.get(
                "footer_text", "Generated by NetShield Dashboard"
            ),
        )

        pdf_buffer = io.BytesIO()
        HTML(string=full_html).write_pdf(pdf_buffer)
        pdf_bytes = pdf_buffer.getvalue()

        logger.info(
            "pdf_generated",
            title=title,
            size_bytes=len(pdf_bytes),
        )

        return pdf_bytes


def get_pdf_service() -> PDFService:
    """Get a PDF service instance."""
    return PDFService()
