"""Schemas package - Pydantic v2 models for API request/response."""

from schemas.common import APIResponse
from schemas.mikrotik import (
    InterfaceInfo,
    ConnectionInfo,
    ARPEntry,
    TrafficData,
    FirewallRule,
    BlockIPRequest,
    UnblockIPRequest,
    LogEntry,
)
from schemas.wazuh import (
    WazuhAgent,
    WazuhAlert,
    ActiveResponseRequest,
)
from schemas.network import (
    IPLabelCreate,
    IPLabelResponse,
    IPGroupCreate,
    IPGroupResponse,
    IPGroupMemberAdd,
)
from schemas.reports import (
    ReportGenerateRequest,
    ReportExportRequest,
    ReportDraft,
)
from schemas.vlan import (
    VlanCreate,
    VlanUpdate,
    VlanInfo,
    VlanTrafficData,
)
from schemas.security import (
    SecurityBlockIPRequest,
    QuarantineRequest,
    GeoBlockRequest,
    CLIMikrotikRequest,
    CLIWazuhAgentRequest,
    CriticalAlert,
    AlertTimelinePoint,
    TopAgent,
    AgentsSummary,
    MitreSummaryItem,
    SystemHealthMikrotik,
    WazuhHealthItem,
    WazuhHealthResponse,
    NetworkSearchResult,
    CLIResponse,
)
from schemas.phishing import (
    PhishingAlert,
    SuspiciousDomain,
    PhishingVictim,
    PhishingStats,
    SinkholeEntryResponse,
    SinkholeRequest,
    PhishingBlockIPRequest,
    PhishingSimulateRequest,
)
from schemas.portal import (
    PortalSession,
    PortalSessionHistory,
    PortalRealtimeStats,
    PortalSummaryStats,
    PortalUser,
    PortalUserCreate,
    PortalUserUpdate,
    PortalUserBulk,
    BulkCreateResult,
    PortalProfile,
    PortalProfileCreate,
    PortalProfileUpdate,
    UnregisteredSpeedUpdate,
    PortalConfig,
    ScheduleConfig,
    ScheduleStatus,
    HotspotSetupResult,
)
from schemas.glpi import (
    GlpiAsset,
    GlpiAssetDetail,
    GlpiAssetCreate,
    GlpiAssetUpdate,
    GlpiAssetStats,
    GlpiAssetHealth,
    GlpiNetworkContext,
    GlpiLocation,
    GlpiTicket,
    GlpiTicketCreate,
    GlpiTicketStatusUpdate,
    GlpiUser,
    GlpiQuarantineRequest,
    GlpiUnquarantineRequest,
    NetworkMaintenanceRequest,
    GlpiAvailability,
)


__all__ = [
    "APIResponse",
    "InterfaceInfo",
    "ConnectionInfo",
    "ARPEntry",
    "TrafficData",
    "FirewallRule",
    "BlockIPRequest",
    "UnblockIPRequest",
    "LogEntry",
    "WazuhAgent",
    "WazuhAlert",
    "ActiveResponseRequest",
    "IPLabelCreate",
    "IPLabelResponse",
    "IPGroupCreate",
    "IPGroupResponse",
    "IPGroupMemberAdd",
    "ReportGenerateRequest",
    "ReportExportRequest",
    "ReportDraft",
    "VlanCreate",
    "VlanUpdate",
    "VlanInfo",
    "VlanTrafficData",
    "SecurityBlockIPRequest",
    "QuarantineRequest",
    "GeoBlockRequest",
    "CLIMikrotikRequest",
    "CLIWazuhAgentRequest",
    "CriticalAlert",
    "AlertTimelinePoint",
    "TopAgent",
    "AgentsSummary",
    "MitreSummaryItem",
    "SystemHealthMikrotik",
    "WazuhHealthItem",
    "WazuhHealthResponse",
    "NetworkSearchResult",
    "CLIResponse",
    "PhishingAlert",
    "SuspiciousDomain",
    "PhishingVictim",
    "PhishingStats",
    "SinkholeEntryResponse",
    "SinkholeRequest",
    "PhishingBlockIPRequest",
    "PhishingSimulateRequest",
]
